import { parseTimestamp } from './text-to-srt';

export interface AssConvertOptions {
  title?: string;
  fontName?: string;
  fontSize?: number;
  playResX?: number;
  playResY?: number;
}

const COLOR_MAP: Record<string, string> = {
  white: 'FFFFFF',
  black: '000000',
  yellow: '00FFFF', // BGR: B=00, G=FF, R=FF
  red: '0000FF',    // BGR: B=00, G=00, R=FF
  green: '00FF00',  // BGR
  blue: 'FF0000',   // BGR: B=FF, G=00, R=00
  cyan: 'FFFF00',   // BGR: B=FF, G=FF, R=00
  aqua: 'FFFF00',
  magenta: 'FF00FF',
  fuchsia: 'FF00FF',
  orange: '0080FF', // BGR
  gray: '808080',
  grey: '808080',
};

/**
 * Format milliseconds into standard ASS timestamp: H:MM:SS.cs
 * e.g., 0:00:01.50 or 1:23:45.67
 */
export function formatAssTimestamp(ms: number): string {
  if (ms < 0) ms = 0;
  const totalSeconds = Math.floor(ms / 1000);
  const milliseconds = ms % 1000;
  const centiseconds = Math.floor(milliseconds / 10);

  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  const hStr = String(hours);
  const mStr = String(minutes).padStart(2, '0');
  const sStr = String(seconds).padStart(2, '0');
  const csStr = String(centiseconds).padStart(2, '0');

  return `${hStr}:${mStr}:${sStr}.${csStr}`;
}

/**
 * Convert HTML-like SRT formatting tags into ASS override tags.
 * e.g. <i> -> {\i1}, </i> -> {\i0}
 * <font color="#RRGGBB"> -> {\c&HBBGGRR&}
 */
export function convertSrtTagsToAss(text: string): string {
  let result = text;

  // Italic
  result = result.replace(/<(?:i|em)>/gi, '{\\i1}');
  result = result.replace(/<\/(?:i|em)>/gi, '{\\i0}');

  // Bold
  result = result.replace(/<(?:b|strong)>/gi, '{\\b1}');
  result = result.replace(/<\/(?:b|strong)>/gi, '{\\b0}');

  // Underline
  result = result.replace(/<u>/gi, '{\\u1}');
  result = result.replace(/<\/u>/gi, '{\\u0}');

  // Strikeout
  result = result.replace(/<(?:s|strike|del)>/gi, '{\\s1}');
  result = result.replace(/<\/(?:s|strike|del)>/gi, '{\\s0}');

  // Font color tags: <font color="#RRGGBB"> or <font color="yellow">
  result = result.replace(/<font\s+[^>]*color=["']?([^"'>\s]+)["']?[^>]*>/gi, (_match, colorVal: string) => {
    let raw = colorVal.trim().toLowerCase();
    if (raw.startsWith('#')) {
      raw = raw.substring(1);
    }

    if (raw.length === 6) {
      const rr = raw.substring(0, 2);
      const gg = raw.substring(2, 4);
      const bb = raw.substring(4, 6);
      const bgr = (bb + gg + rr).toUpperCase();
      return `{\\c&H${bgr}&}`;
    }

    if (COLOR_MAP[raw]) {
      return `{\\c&H${COLOR_MAP[raw]}&}`;
    }

    return '';
  });

  result = result.replace(/<\/font>/gi, '{\\c}');

  // Strip any remaining arbitrary HTML tags
  result = result.replace(/<\/?[a-z][a-z0-9]*[^<>]*>/gi, '');

  return result;
}

/**
 * Main function: Convert SubRip (.srt) content into Advanced SubStation Alpha (.ass)
 */
export function convertSrtToAss(srtContent: string, options: AssConvertOptions = {}): string {
  // Strip BOM and normalize line breaks
  const normalized = srtContent.replace(/^\uFEFF/, '').replace(/\r\n/g, '\n').trim();
  if (!normalized) return '';

  const title = options.title || 'Converted Subtitles';
  const fontName = options.fontName || 'Arial';
  const fontSize = options.fontSize || 48;
  const playResX = options.playResX || 1920;
  const playResY = options.playResY || 1080;

  const headerLines: string[] = [
    '[Script Info]',
    `; Script generated by SRTConverters.com - Free In-Browser Subtitle Converter`,
    `Title: ${title}`,
    `Original Script: SRTConverters.com`,
    `ScriptType: v4.00+`,
    `WrapStyle: 0`,
    `ScaledBorderAndShadow: yes`,
    `YCbCr Matrix: None`,
    `PlayResX: ${playResX}`,
    `PlayResY: ${playResY}`,
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    `Style: Default,${fontName},${fontSize},&H00FFFFFF,&H000000FF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,1,2,20,20,30,1`,
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
  ];

  // Split by empty lines to find subtitle blocks
  const blocks = normalized.split(/\n\s*\n/);
  const events: string[] = [];

  for (const block of blocks) {
    const lines = block.split('\n').map((l) => l.trim()).filter((l) => l.length > 0);
    if (lines.length === 0) continue;

    // Find the timestamp line containing '-->'
    let timeLineIdx = -1;
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].includes('-->')) {
        timeLineIdx = i;
        break;
      }
    }

    if (timeLineIdx === -1) continue;

    const timeLine = lines[timeLineIdx];
    const timeParts = timeLine.split('-->');
    if (timeParts.length !== 2) continue;

    const startStr = timeParts[0].trim();
    const endStr = timeParts[1].trim().split(/\s+/)[0]; // strip any trailing placement attributes

    const startMs = parseTimestamp(startStr);
    const endMs = parseTimestamp(endStr);

    const startAss = formatAssTimestamp(startMs);
    const endAss = formatAssTimestamp(endMs);

    // Dialogue text lines
    const textLines = lines.slice(timeLineIdx + 1);
    if (textLines.length === 0) continue;

    const convertedLines = textLines.map((line) => convertSrtTagsToAss(line));
    // ASS uses \N for hard line break inside dialogue text
    const dialogueText = convertedLines.join('\\N');

    events.push(`Dialogue: 0,${startAss},${endAss},Default,,0,0,0,,${dialogueText}`);
  }

  if (events.length === 0) {
    return headerLines.join('\n') + '\n';
  }

  return headerLines.join('\n') + '\n' + events.join('\n') + '\n';
}

export interface AssToSrtOptions {
  preserveBasicFormatting?: boolean;
  ignoreComments?: boolean;
}

/**
 * Parse an ASS timestamp string into milliseconds.
 * ASS timestamps are formatted as H:MM:SS.cs (centiseconds) or H:MM:SS.mmm
 * e.g., "0:01:23.45" or "00:01:23.45" or "1:02:03.456"
 */
export function parseAssTimestamp(timestamp: string): number {
  if (!timestamp) return 0;
  const clean = timestamp.trim();
  const parts = clean.split(':');
  if (parts.length < 2) return 0;

  let hours = 0;
  let minutes = 0;
  let secAndFraction = '';

  if (parts.length === 3) {
    hours = parseInt(parts[0], 10) || 0;
    minutes = parseInt(parts[1], 10) || 0;
    secAndFraction = parts[2];
  } else {
    minutes = parseInt(parts[0], 10) || 0;
    secAndFraction = parts[1];
  }

  const [secStr, fractionStr = '0'] = secAndFraction.split('.');
  const seconds = parseInt(secStr, 10) || 0;

  let fractionMs = 0;
  if (fractionStr.length === 2) {
    // 2 digits = centiseconds (e.g., .45 -> 450ms)
    fractionMs = parseInt(fractionStr, 10) * 10;
  } else if (fractionStr.length === 3) {
    // 3 digits = milliseconds (e.g., .450 -> 450ms)
    fractionMs = parseInt(fractionStr, 10);
  } else if (fractionStr.length === 1) {
    fractionMs = parseInt(fractionStr, 10) * 100;
  } else if (fractionStr.length > 3) {
    fractionMs = parseInt(fractionStr.substring(0, 3), 10);
  }

  return hours * 3600000 + minutes * 60000 + seconds * 1000 + fractionMs;
}

/**
 * Format milliseconds into standard SubRip (.srt) timestamp: HH:MM:SS,mmm
 * e.g., 00:01:23,450
 */
export function formatSrtTimestamp(ms: number): string {
  if (ms < 0) ms = 0;
  const totalSeconds = Math.floor(ms / 1000);
  const milliseconds = ms % 1000;

  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  const hStr = String(hours).padStart(2, '0');
  const mStr = String(minutes).padStart(2, '0');
  const sStr = String(seconds).padStart(2, '0');
  const msStr = String(milliseconds).padStart(3, '0');

  return `${hStr}:${mStr}:${sStr},${msStr}`;
}

/**
 * Convert ASS override tags into clean SRT text or basic HTML tags.
 * Converts \N and \n into newlines, \h into spaces.
 * Optionally retains <b>, <i>, <u>, <s> while stripping positioning (\pos, \an),
 * colors (\c), fades (\fad), karaoke (\k), and vector drawings (\p1).
 */
export function convertAssTagsToSrt(text: string, preserveBasicFormatting = true): string {
  if (!text) return '';

  let result = text;

  // 1. Remove ASS vector drawing blocks: {\p[1-9]...}...{\p0...}
  result = result.replace(/\{\\p[1-9][^}]*\}[\s\S]*?\{\\p0[^}]*\}/gi, '');
  result = result.replace(/\{\\p[1-9][^}]*\}.*$/gi, '');

  // 2. Line break tags to standard newlines
  result = result.replace(/\\N/g, '\n');
  result = result.replace(/\\n/g, '\n');

  // 3. Hard space \h to regular space
  result = result.replace(/\\h/g, ' ');

  if (preserveBasicFormatting) {
    // Convert bold tags: \b1 or \b<weight> -> <b>, \b0 -> </b>
    result = result.replace(/\{\\b(?:[1-9]\d*|1)\}/gi, '<b>');
    result = result.replace(/\{\\b0\}/gi, '</b>');

    // Convert italic tags: \i1 -> <i>, \i0 -> </i>
    result = result.replace(/\{\\i1\}/gi, '<i>');
    result = result.replace(/\{\\i0\}/gi, '</i>');

    // Convert underline tags: \u1 -> <u>, \u0 -> </u>
    result = result.replace(/\{\\u1\}/gi, '<u>');
    result = result.replace(/\{\\u0\}/gi, '</u>');

    // Convert strikeout tags: \s1 -> <s>, \s0 -> </s>
    result = result.replace(/\{\\s1\}/gi, '<s>');
    result = result.replace(/\{\\s0\}/gi, '</s>');
  }

  // 4. Strip any remaining ASS override tag blocks: {...}
  result = result.replace(/\{[^\}]*\}/g, '');

  if (!preserveBasicFormatting) {
    // Strip any HTML formatting tags
    result = result.replace(/<\/?[a-z][a-z0-9]*[^<>]*>/gi, '');
  } else {
    // Clean up empty tags like <b></b> or <i></i>
    result = result.replace(/<([a-z]+)>\s*<\/\1>/gi, '');
  }

  // Trim excess spaces around lines
  return result
    .split('\n')
    .map((line) => line.trim())
    .join('\n')
    .trim();
}

/**
 * Split a comma-separated line with a limit, keeping all remaining text in the last element.
 */
function splitCsvWithLimit(line: string, limit: number): string[] {
  const result: string[] = [];
  let currentIndex = 0;

  for (let i = 0; i < limit - 1; i++) {
    const nextComma = line.indexOf(',', currentIndex);
    if (nextComma === -1) {
      break;
    }
    result.push(line.substring(currentIndex, nextComma).trim());
    currentIndex = nextComma + 1;
  }

  result.push(line.substring(currentIndex).trim());
  return result;
}

interface SrtCue {
  startMs: number;
  endMs: number;
  text: string;
}

/**
 * Main function: Convert Advanced SubStation Alpha (.ass / .ssa) content to SubRip (.srt)
 */
export function convertAssToSrt(assContent: string, options: AssToSrtOptions = {}): string {
  const normalized = assContent.replace(/^\uFEFF/, '').replace(/\r\n/g, '\n').trim();
  if (!normalized) return '';

  const preserveFormatting = options.preserveBasicFormatting !== false;
  const ignoreComments = options.ignoreComments !== false;

  const lines = normalized.split('\n');

  let inEvents = false;
  // Default ASS format column order
  let startIdx = 1;
  let endIdx = 2;
  let textIdx = 9;
  let expectedCols = 10;

  const cues: SrtCue[] = [];

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i].trim();
    if (!rawLine) continue;

    // Check for section headers
    if (rawLine.startsWith('[') && rawLine.endsWith(']')) {
      inEvents = rawLine.toLowerCase() === '[events]';
      continue;
    }

    // Parse format line inside [Events]
    if (inEvents && rawLine.toLowerCase().startsWith('format:')) {
      const formatStr = rawLine.substring(7).trim();
      const cols = formatStr.split(',').map((c) => c.trim().toLowerCase());
      expectedCols = cols.length;

      const sIdx = cols.indexOf('start');
      const eIdx = cols.indexOf('end');
      const tIdx = cols.indexOf('text');

      if (sIdx !== -1) startIdx = sIdx;
      if (eIdx !== -1) endIdx = eIdx;
      if (tIdx !== -1) textIdx = tIdx;
      continue;
    }

    // Process dialogue lines (even if [Events] header was omitted in lenient files)
    const isDialogue = rawLine.toLowerCase().startsWith('dialogue:');
    const isComment = rawLine.toLowerCase().startsWith('comment:');

    if (!isDialogue && (!isComment || ignoreComments)) {
      continue;
    }

    const colonIdx = rawLine.indexOf(':');
    if (colonIdx === -1) continue;

    const dataPart = rawLine.substring(colonIdx + 1).trim();
    const cols = splitCsvWithLimit(dataPart, expectedCols);

    if (cols.length <= Math.max(startIdx, endIdx)) continue;

    const startStr = cols[startIdx] || '';
    const endStr = cols[endIdx] || '';
    const rawText = cols[textIdx] !== undefined ? cols[textIdx] : cols[cols.length - 1] || '';

    const startMs = parseAssTimestamp(startStr);
    const endMs = parseAssTimestamp(endStr);

    const cleanedText = convertAssTagsToSrt(rawText, preserveFormatting);
    if (!cleanedText) continue;

    cues.push({
      startMs,
      endMs,
      text: cleanedText,
    });
  }

  if (cues.length === 0) return '';

  // Sort cues chronologically
  cues.sort((a, b) => a.startMs - b.startMs || a.endMs - b.endMs);

  // Format into standard numbered SRT blocks
  const srtBlocks = cues.map((cue, index) => {
    const srtIndex = index + 1;
    const timeLine = `${formatSrtTimestamp(cue.startMs)} --> ${formatSrtTimestamp(cue.endMs)}`;
    return `${srtIndex}\n${timeLine}\n${cue.text}`;
  });

  return srtBlocks.join('\n\n') + '\n';
}

